#use_frameworks!
platform :ios, '8.0'

target 'SANetwork_Example' do
  pod 'SANetwork', :path => '../'
  pod 'AFNetworking'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 0.9.2'
end

target :SANetwork_ExampleTests do
    pod 'SANetwork', :path => '../'
end
